name: Release Framework

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'make a tag for the cloud-native-golang-framework'
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "mrflick72"
          git config user.email "valerio.vaudi@gmail.com"
      - name: Create tag
        run: |
          git tag -a ${{github.event.inputs.version}} -m "tag a new cloud-native-golang-framework version: ${{github.event.inputs.version}}"
          git push --tags